name: Tibia Boot Monitor

on:
  schedule:
    - cron: '01 8 * * *'  # 05:01 GMT-3 → 08:01 UTC
  workflow_dispatch:       # permite rodar manualmente também

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          pip install requests

      - name: Executar script Tibia Boot
        env:
          GOOGLE_SCRIPT_URL: ${{ secrets.GOOGLE_SCRIPT_URL }}
        run: |
          python tibia_boot.py
