# Agendamento para rodar todo dia às 05:00 GMT-3 (08:00 UTC)  
on:  
  schedule:  
    - cron: '0 8 * * *'   
  workflow_dispatch:  
  
jobs:  
  monitor:  
    runs-on: ubuntu-latest  
  
    steps:  
      # Passo 1: Checar o código do repositório  
      - name: Checkout repository  
        uses: actions/checkout@v3  
  
      # Passo 2: Configurar Python  
      - name: Setup Python  
        uses: actions/setup-python@v4  
        with:  
          python-version: '3.11'  
  
      # Passo 3: Instalar dependências  
      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip  
          pip install requests  
  
      # Passo 4: Executar script Python  
      - name: Run server boot monitor  
        env:  
          GOOGLE_SCRIPT_URL: ${{ secrets.GOOGLE_SCRIPT_URL }}  
        run: |  
          python tibia_boot.py
