name: Tibia Boot Notifier

on:
  schedule:
    # Cron para rodar às 05:01 BRT todo dia (05:01UTC)
    - cron: '01 8 * * *'
  workflow_dispatch: # permite rodar manualmente

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checar repositório
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar dependências
      run: pip install requests

    - name: Rodar script
      run: python tibia_boot.py
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        PHONE_NUMBER_ID: ${{ secrets.PHONE_NUMBER_ID }}
        DESTINO: ${{ secrets.DESTINO }}
